
**stdout:**
b'  \xe2\x9c\x98 Runtime Error\n  \xe2\x9c\x98 0/57 cases passed (N/A)\n  \xe2\x9c\x98 Error: Line 74: TypeError: inf is not valid value for the expected return type integer\n  \xe2\x9c\x98 Error: TypeError: inf is not valid value for the expected return type integer\n    raise TypeError(str(ret) + " is not valid value for the expected return type integer");\nLine 74 in _driver (Solution.py)\n    _driver()\nLine 81 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nException: Error when serializing long: inf out of range [-(2^53-1), 2^53-1]\nLine 15 in _serialize_int (./python3/__serializer__.py)\nLine 63 in _serialize (./python3/__serializer__.py)\n    out = ser._serialize(ret, \'integer\')\nLine 72 in _driver (Solution.py)\n  \xe2\x9c\x98 Testcase: "WRRBBW"\n"RB"\n  \xe2\x9c\x98 Answer: \n  \xe2\x9c\x98 Expected Answer: -1\n  \xe2\x9c\x98 Stdout: \n'
**stderr:**
b"- Sending code to judge\n(node:79837) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency\n(Use `node --trace-warnings ...` to show where the warning was created)\n- Waiting for judge result\n- Waiting for judge result\n- Waiting for judge result\n- Waiting for judge result\n- Waiting for judge result\n"