
**stdout:**
b'  \xe2\x9c\x98 Runtime Error\n  \xe2\x9c\x98 3/70 cases passed (N/A)\n  \xe2\x9c\x98 Error: Line 55: TypeError: None is not valid value for the expected return type integer\n  \xe2\x9c\x98 Error: TypeError: None is not valid value for the expected return type integer\n    raise TypeError(str(ret) + " is not valid value for the expected return type integer");\nLine 55 in _driver (Solution.py)\n    _driver()\nLine 62 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nTypeError: \'<\' not supported between instances of \'int\' and \'NoneType\'\nLine 14 in _serialize_int (./python3/__serializer__.py)\nLine 63 in _serialize (./python3/__serializer__.py)\n    out = ser._serialize(ret, \'integer\')\nLine 53 in _driver (Solution.py)\n  \xe2\x9c\x98 Testcase: 3\n6\n4\n  \xe2\x9c\x98 Answer: \n  \xe2\x9c\x98 Expected Answer: 8\n  \xe2\x9c\x98 Stdout: \n'
**stderr:**
b"- Sending code to judge\n(node:72438) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency\n(Use `node --trace-warnings ...` to show where the warning was created)\n- Waiting for judge result\n- Waiting for judge result\n- Waiting for judge result\n- Waiting for judge result\n"